/**
 * Route roles
 */

// ADMIN ONLY
export const ADMIN_ONLY = [

    'ADMIN'
];

// ADMIN AND DIRECTION
export const ADMIN_AND_DIRECTION = [

    'ADMIN',

    'DIRECTION'
];

// ADMIN AND RESPONSABLE_FORMATION
export const ACADEMIC_ROLES = [

    'ADMIN',

    'RESPONSABLE_FORMATION'
];

// ADMIN, RESPONSABLE_FORMATION, SECRETAIRE AND ADMINISTRATIF
export const STUDENT_MANAGEMENT_ROLES = [

    'ADMIN',

    'RESPONSABLE_FORMATION',

    'SECRETAIRE',

    'ADMINISTRATIF'
];

// ADMIN, SECRETAIRE AND ADMINISTRATIF
export const HR_ROLES = [

    'ADMIN',

    'SECRETAIRE',

    'ADMINISTRATIF'
];

// ADMIN, INSERTION AND APPUI_INSERTION
export const INSERTION_ROLES = [

    'ADMIN',

    'INSERTION',

    'APPUI_INSERTION'
];

// ADMIN, RESPONSABLE_FORMATION, ENSEIGNANT, ENSEIGNANT_ASSOCIE, TUTEUR AND ETUDIANT
export const TEACHING_ROLES = [

    'ADMIN',

    'RESPONSABLE_FORMATION',

    'ENSEIGNANT',

    'ENSEIGNANT_ASSOCIE',

    'TUTEUR',

    'ETUDIANT'
];

// ADMIN, DIRECTION AND RESPONSABLE_FORMATION
export const MEETING_ROLES = [

    'ADMIN',

    'DIRECTION',

    'RESPONSABLE_FORMATION'
];

// ADMIN, SECRETAIRE, ADMINISTRATIF AND RESPONSABLE_FORMATION
export const COMMUNICATION_ROLES = [

    'ADMIN',

    'SECRETAIRE',

    'ADMINISTRATIF',

    'RESPONSABLE_FORMATION'
];

// ADMIN, DIRECTION, SECRETAIRE, RESPONSABLE_FORMATION, ADMINISTRATIF, INSERTION, APPUI_INSERTION, ENSEIGNANT, ENSEIGNANT_ASSOCIE, TUTEUR AND ETUDIANT
export const ALL_AUTHENTICATED_ROLES = [

    'ADMIN',

    'DIRECTION',

    'SECRETAIRE',

    'RESPONSABLE_FORMATION',

    'ADMINISTRATIF',

    'INSERTION',

    'APPUI_INSERTION',

    'ENSEIGNANT',

    'ENSEIGNANT_ASSOCIE',

    'TUTEUR',

    'ETUDIANT'
];

// ADMIN, DIRECTION, SECRETAIRE, ADMINISTRATIF, RESPONSABLE_FORMATION, ENSEIGNANT, ENSEIGNANT_ASSOCIE, TUTEUR AND ETUDIANT
export const DASHBOARD_ROLES = [

    'ADMIN',

    'DIRECTION',

    'SECRETAIRE',

    'ADMINISTRATIF',

    'RESPONSABLE_FORMATION',

    'ENSEIGNANT',

    'ENSEIGNANT_ASSOCIE',

    'TUTEUR',

    'ETUDIANT'
];